### ISSUE TITLE
Drop MongoDB image to 4.4 (or documentation fix for 5.0)

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/docker-compose#14]
The result of a recent support case is that MongoDB `4.4` is the latest release compatible with Graylog Server `4.3`.  This project currently references image `mongodb:5.0`.

* If `5.0` is supported, https://docs.graylog.org/docs should be updated to reflect the compatibility
* If `5.0` is _not_ supported, this project should drop back down to `mongodb:4.4`

[ HS #1000676139 ]

**Comment by coffee-squirrel** [comment]
Based upon https://github.com/Graylog2/graylog2-server/pull/13778#issuecomment-1291771475 and https://github.com/Graylog2/graylog2-server/pull/13791 it seems 5.0 is alright after all-- at least for `4.3.x` and `5.0.x`.

Leaving open as the docs, at least, still need an update to reflect this.  I'll also point out that support case 1000676139 (checking for the max compatible/supported MongoDB version) got us an incorrect answer.

**Comment by bernd** [comment]
We updated the Docker Compose files to use MongoDB 5.0. Thanks for the heads up!
