### ISSUE TITLE
Failing with com.mongodb.MongoSocketException: mongodb: Temporary failure in name resolution

### ISSUE THREAD

**Issue by ThatCoffeeGuy** [Graylog2/docker-compose#17]
Using the unmodified version of the supplied core docker-compose.yaml and .env files (besides changing the passwords and GRAYLOG_HTTP_EXTERNAL_URI),

mongodb just fails with the above message. I am not exactly sure why would it try to resolve any servers, from the compose file it's looking like some internal linking that just should work.

```    
GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
```

Executed on this system:

```
Linux server 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Docker version 20.10.18, build b40c2f6
Docker Compose version v2.11.2
````
Same result with apt's compose (I tried with this first, then updated to v2.11.2):

```
docker-compose version 1.29.2, build unknown
```

**Comment by ThatCoffeeGuy** [comment]
Confirmed, that's exactly what happened.

Model name:            Common KVM processor
    CPU family:          15
    Model:               6
    Thread(s) per core:  1
    Core(s) per socket:  4
    Socket(s):           2
    Stepping:            1
    BogoMIPS:            5600.00
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti

vs

 Model name:            Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
    CPU family:          6
    Model:               62
    Thread(s) per core:  1
    Core(s) per socket:  4
    Socket(s):           2
    Stepping:            4
    BogoMIPS:            5600.00
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 cx16 pdcm pcid sse4_1 sse4_2 x2a
                         pic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cpuid_fault pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms xsaveopt arat umip md_clear arch_capabilities
                         
                    
The solution is to execute with proper instructionsets available. :)

**Comment by bernd** [comment]
@ThatCoffeeGuy Thank you for the update! :pray:
