### ISSUE TITLE
Opensearch always crashes

### ISSUE THREAD

**Issue by marco74** [Graylog2/docker-compose#26]
Hello,

in my case OpenSearch always crashes with exit code 137:

```
Killing performance analyzer process 102
./opensearch-docker-entrypoint.sh: line 116:   101 Killed                  "$@" "${opensearch_opts[@]}"
OpenSearch exited with code 137
Performance analyzer exited with code 143
```

Therefore graylog2 get's into an unhealty state.

The only thing I did is settring the two passwords in `.env`

Regards Marco

**Comment by janheise** [comment]
hi @marco74 

can you please be a bit more specific: 
- which of the available docker-compose.yml are you using?
- hardware/OS?

I just did a small test with the open-core one and it works fine here.

**Comment by marco74** [comment]
Hi @janheise ,
thank you for your fast reply. After reading the logs more brief I realized two things concerning opensearch: First it is written in java. You can say what you want but I just hate it, because it uses enormous ressources, the second thing is, that it might be a fork of elasticsearch.

I also found out that the kill came from the VM on my laptop – it's just a first test. So I restarted the vm with more RAM now it works.

BTW: started the open-core compose file yes.

Regards

Marco
