### ISSUE TITLE
Error: Preflight check failed with error: Journal directory </usr/share/graylog/data/journal> has not enought free space (1707 MB) available

### ISSUE THREAD

**Issue by joykim93** [Graylog2/docker-compose#31]
Hi, I'm pretty new with graylog.
I tried to run it by docker-compose.yml file (open-core ver.), but I faced with following errors:

![image](https://github.com/Graylog2/docker-compose/assets/87594392/d108ff3a-1f09-4b1f-939a-a970223f6848)

Please give any advices to resolve this issue.

Environemnt:
- OS Information : Amazon Linux
- Mongodb 5.0
- Opensearch 2.4.0
- Graylog 5.0

**Comment by bernd** [comment]
@joykim93 You need to increase the disk space for the partition containing the `message_journal_dir` directory.
