### ISSUE TITLE
New here! however I am stuck and was wondering if I can get assistance ? 

### ISSUE THREAD

**Issue by DonRCI** [Graylog2/docker-compose#38]
Pulled down a local of the graylog demo repo. Im on Windows using Docker Desktop and Visual Studio Code as an IDE. I followed the quick guide under the git repo for startup. But when running docker compose up, Im getting no config found ? did I miss a step ? Also there are 3 .env.example files do all three need to be edited and updated with the secret ?

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
