### ISSUE TITLE
permission denied after starting

### ISSUE THREAD

**Issue by necrofrost** [Graylog2/docker-compose#4]
I've ran the docker-compose file, but ran into an issue. after doing "docker logs graylog_graylog_1" I can see the last error: 

> ERROR: Unable to access file /usr/share/graylog/data/journal/graylog2-committed-read-offset: Permission denied"

maybe it has to do with the fact that I had to change the volumes to:

```
volumes:
      - ./data/graylog_data/:/usr/share/graylog/data/data
      - ./data/graylog_journal/:/usr/share/graylog/data/journal
```

**Comment by Ralms** [comment]
What was the solution for this? 
I'm having the same issue, I've tried letting docker create the folders, creating them myself, creating with sudo, nothing is working.

**Comment by Ralms** [comment]
Well, to leave here for others, I pretty much granted o+wx and g+wx permissions with chmod to the folders mounts.

**Comment by RogueGhost93** [comment]
same issue here, any solution to this? If i define volumes at the bottom of docker-compose file and let docker take care of that then everything works. If i define volumes myself like 
      - ./data/graylog_data/:/usr/share/graylog/data/data
      - ./data/graylog_journal/:/usr/share/graylog/data/journal
 regardless of the permissions that i set i still get permission denied errors in graylog logs....
