### ISSUE TITLE
confusing documentation

### ISSUE THREAD

**Issue by cxnky** [Graylog2/docker-compose#50]
i'm trying to upgrade from 5.0 to 5.2, and i have pulled the latest version of this repo down, and attempted to run the docker-compose file within open-core. it starts up fine, but then the graylog instance itself just keeps saying 

```2024-01-04 08:21:06,275 INFO : org.graylog2.storage.versionprobe.VersionProbe - OpenSearch/Elasticsearch is not available. Retry #41
2024-01-04 08:21:11,276 ERROR: org.graylog2.storage.versionprobe.VersionProbe - Unable to retrieve version from Elasticsearch node: Failed to connect to /127.0.0.1:9200. - Connection refused.
2024-01-04 08:21:11,277 INFO : org.graylog2.storage.versionprobe.VersionProbe - OpenSearch/Elasticsearch is not available. Retry #42
```

yet the docker compose file doesn't have opensearch in there. is it needed or not?

**Comment by janheise** [comment]
@cxnky Hi, can you give some more context? You used an older version of the `docker-compose.yml` with 5.0 and now replaced the `docker-compose.yml` with the current version of the file from the repo? This won't work. In case you just want to upgrade graylog to 5.2, you should just reference the new version in your old, existing `docker-compose.yml`.

**Comment by janheise** [comment]
Closing it because of missing feedback.
