### ISSUE TITLE
Graylog images still point to v5.2

### ISSUE THREAD

**Issue by systemboogie** [Graylog2/docker-compose#69]
I came here from https://graylog.org/downloads/ where it currently says I can get Graylog at version 6.0.3. However, everything in here still points to version 5.2. Not sure what's involved other than bumping the Graylog image version, so I'll just leave it here.

<img width="471" alt="Screenshot 2024-07-03 at 10 48 11" src="https://github.com/Graylog2/docker-compose/assets/16419901/e371e515-d4e1-4e8c-bed3-e7b54775dab6">

**Comment by sethgraylog** [comment]
@systemboogie Are you referencing the Docker Compose example files specifically? I checked the other links and these are linking to 6.03. The Docker Compose example YAML files were still referencing 5.2. Architecture has updated these example files to 6.03 which I believe should resolve the issue. Please re-open if you still see an issue.

**Comment by systemboogie** [comment]
@sethgraylog Yes, just the Docker Compose files. It's fixed with https://github.com/Graylog2/docker-compose/commit/e128f0f8c288eea1a07239a5b2fbae02d2afb5c9. Thanks a lot!
