### ISSUE TITLE
How to access graylog-datanode's API to reschedule shards?

### ISSUE THREAD

**Issue by f0o** [Graylog2/docker-compose#70]
I've got a bunch of failing shards that I'd like to investigate through _cluster/allocation/explain and possibly cause rescheduling.

However I keep getting `authentication finally failed` when curling the datanode:9200.

What are the credentials for the node or where are they stored?

**Comment by moesterheld** [comment]
If you are using Graylog/Data node 6.0, you can go to System/Data node/Configuration and generate a client certificate to use for calling the datanode OS api.
Or, as an alternative, you can use the Graylog endpoint which proxies calls to the api with a regular Graylog authentication token: `api/datanodes/any/opensearch/_cluster/allocation/explain`

**Comment by f0o** [comment]
Did not know that graylog can proxy my calls - will give it a shot!

**Comment by f0o** [comment]
Marking as resolved - easier to use the graylog instance as proxy :)
