### ISSUE TITLE
main ERROR Deprecated log4j.xml setting detected

### ISSUE THREAD

**Issue by dropthemasquerade** [Graylog2/docker-compose#74]
I was trying to run the open-core's docker-compose, and got the below error

`
datanode-1  | 2024-09-13T10:17:26.896315044Z main ERROR Deprecated log4j.xml setting detected <bufferSize="500"> Using default <bufferSizeBytes=50MB> instead
datanode-1  | 2024-09-13T10:17:28.460Z INFO  [ImmutableFeatureFlagsCollector] Following feature flags are used: {}
datanode-1  | 2024-09-13T10:17:28.911Z ERROR [CmdLineTool] Invalid configuration
`

How can I fixed it?

**Comment by sethgraylog** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this looks like you need support. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
