### ISSUE TITLE
README.md - how is this not production-ready?

### ISSUE THREAD

**Issue by tom-cook-pmev** [Graylog2/docker-compose#8]
README.md suggests that a server started in this way is not production-ready (says it is "for testing or demo purposes").

It would be useful if the file gave some sort of pointer to what would need to be done to make it production-ready.

**Comment by malcyon** [comment]
I think normally for production, you'd want a cluster with separate instances for Elasticsearch and Graylog. Like described here under "Bigger Production Setup".

https://docs.graylog.org/docs

The idea with this is you can just run `docker-compose up` and you get a full Graylog instance to poke around on. But it's all on one node, so if that goes down, it's out of commisson. 

I'd probably also want authentication and HTTPS setup for everything.

I'm probably not the best person to answer this, though. @bernd or @kroepke could probably say more.

**Comment by bernd** [comment]
What @malcyon said. :slightly_smiling_face:
